version: '3.7'

services:
    zookeper:
        image: zookeeper:3.4.9
        hostname: zookeper
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zookeper:2888:3888
        volumes:
            - ./.data/zookeper/data:/data
            - ./.data/logs/zookeper/datalog:/datalog

    kafka:
        image: confluentinc/cp-kafka:5.5.1
        hostname: kafka
        environment:
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zookeper:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - ./.data/kafka/data:/var/lib/kafka/data
        depends_on:
            - zookeper

    app:
        build: .
        depends_on:
            - kafka
        links:
            - kafka
        volumes:
            - ".:/app"
