version: '3.7'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
        volumes:
            - ./.data/zookeper/data:/data
            - ./.data/logs/zookeper/datalog:/datalog

    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        volumes:
            - ./.data/kafka/data:/var/lib/kafka/data
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/local
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "test-topic:2:1,test-topic2:1:1,test-topic3:1:1"

    app:
        build: .
        depends_on:
            - kafka
        links:
            - kafka
        volumes:
            - ".:/app"
