version: '3.7'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
        volumes:
            - ./.data/zookeper/data:/data
            - ./.data/logs/zookeper/datalog:/datalog

    kafdrop:
        image: obsidiandynamics/kafdrop
        restart: "no"
        ports:
            - "9000:9000"
        environment:
            KAFKA_BROKERCONNECT: "kafka:29092"
            JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
        depends_on:
            - "kafka"

    kafka:
        image: wurstmeister/kafka
        volumes:
            - ./.data/kafka/data:/var/lib/kafka/data
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/local
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "test-topic:2:1,test-topic2:1:1,test-topic3:1:1"
            KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
            KAFKA_RESTART_ATTEMPTS: "10"
            KAFKA_RESTART_DELAY: "5"
            ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

    app:
        build: .
        depends_on:
            - kafka
        links:
            - kafka
        volumes:
            - ".:/app"
